import HomePage from "@/components/Homepage";
import NewChat from "@/components/NewChat";
import Sidebar from "@/components/Sidebar";
import Topbar from "@/components/Topbar";
import Head from "next/head";
import { useEffect, useRef } from "react";
import { useGlobalContext } from "../context";

export default function Home() {
  const { isSidebarOpen } = useGlobalContext();



  return (
    <>
      <Head>
        <title>ChatBPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    <div className="w-full"> 
     <Topbar />
<div className="max-w-[1400px] mx-auto  md:flex pb-24  ">
  <Sidebar />
    <HomePage />
</div>
      </div> 

    </>
  );
}
